### ISSUE TITLE
Testtreiber searchOrganizationInFhirDirectory.contactMxid unklar

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#175]
Im Testtreiber "searchOrganizationInFhirDirectory" definieren sie folgenden Suchparameter:
```yaml
        - name: contactMxid
          in: query
          description: "MXID of the Organization.contact."
          schema:
            type: string
```

Die FHIR Beispiele im Simplifier, wie auch die HL7 Spezifikation der Organization lassen nicht klar darauf schliessen, wonach hier gesucht werden soll.
Können Sie entweder
- das OrganizationExample im Simplifier entsprechend erweitern oder
- den Suchparameter liquidieren.

Besten Dank
